"""new fields in user model

Revision ID: 86281b9d637e
Revises: 6d20b6ad7fda
Create Date: 2019-10-29 14:59:07.086191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86281b9d637e'
down_revision = '6d20b6ad7fda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
