"""update item

Revision ID: 8a3595fe7a78
Revises: 5cbdbbfd3390
Create Date: 2019-11-04 09:42:29.543554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3595fe7a78'
down_revision = '5cbdbbfd3390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('mtype', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'mtype')
    # ### end Alembic commands ###
