"""poinvestments tables

Revision ID: bfa7c103a5c4
Revises: 8a3595fe7a78
Create Date: 2019-11-08 14:46:58.555982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa7c103a5c4'
down_revision = '8a3595fe7a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('category', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_category'), 'investment', ['category'], unique=False)
    op.create_index(op.f('ix_investment_title'), 'investment', ['title'], unique=True)
    op.create_table('position',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('investment', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('position', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['investment'], ['investment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_date'), 'position', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_position_date'), table_name='position')
    op.drop_table('position')
    op.drop_index(op.f('ix_investment_title'), table_name='investment')
    op.drop_index(op.f('ix_investment_category'), table_name='investment')
    op.drop_table('investment')
    # ### end Alembic commands ###
